Prefix: '&6[&aFrame&bEconomy&6] &c>> &7'

# MySQL Connection!
MySQL:
  Host: 'localhost'
  User: 'root'
  Password: 'password'
  Database: 'database'
  Port: 3306
  Use: false
SQLite:
  Path: 'plugins/FrameEconomy/money'
  FileName: 'database'
  Use: false
MongoDB:
  Database: ' '
  User: ' '
  Password: ' '
  Host: ' '
  Port: 27017
  Localhost: false
  Normal: false
  Use: false
  CollectionName: 'frameeconomy_economy'
Currency:
  Plural: '$'
  Singular: '$'
Economy:
  MaxBalance: 1000000000

# PayLoad send's Money in the Time was set to OfflinePlayer
PayLoad:
  Sec: 0
  Min: 0
  Hour: 1
  Day: 0
  Amount: 100.0
  Use: false
Interest:
  Percent: 1.25
  Amount: 10
  Sec: 0
  Min: 0
  Hour: 1
  Day: 0
  Use: false