#MySQL Connection!
MySQL:
  Host: ' '
  User: ' '
  Password: ' '
  Database: ' '
  Port: 3306
  Use: false
Currency:
  Plural: '$'
  Singular: '$'
Economy:
  Activate: false
  MaxBalance: 1000000
PayLoad:
  Use: false
  Time:
    Sec: 0
    Min: 30
    Hour: 0
    Day: 0