name: FrameEconomy
version: @version@
description: Money System works with Vault
main: de.framedev.frameeconomy.main.Main
api-version: 1.13
depend: [ Vault ]
authors: [ FrameDev ]
website: https://framedev.stream

commands:
  pay:
  balance:
    aliases:
      - bal
  economy:
    aliases:
      - eco
  balancetop:
    aliases:
      - baltop
  bank:
permissions:
  frameeconomy.*:
    children:
      frameeconomy.balance: true
      frameeconomy.balance.others: true
      frameeconomy.balancetop: true
      frameeconomy.pay: true
      frameeconomy.eco.set: true
      frameeconomy.eco.set.others: true
      frameeconomy.bank.create: true
      frameeconomy.bank.balance: true
      frameeconomy.bank.deposit: true
      frameeconomy.bank.withdraw: true
  frameeconomy.balance:
    default: op
  frameeconomy.balance.others:
    default: op
    children:
      frameeconomy.balance: true
  frameeconomy.pay:
    default: op
  frameeconomy.eco.set:
    default: op
  frameeconomy.eco.set.others:
    default: op
    children:
      frameeconomy.eco.set: true
  frameeconomy.balancetop:
    default: op
  frameeconomy.bank.create:
    default: op
  frameeconomy.bank.balance:
    default: op
  frameeconomy.bank.deposit:
    default: op
  frameeconomy.bank.withdraw:
    default: op