name: FrameEconomy
version: @version@
description: Money System works with Vault
main: de.framedev.frameeconomy.main.Main
api-version: 1.13
depend: [ Vault ]
authors: [ FrameDev ]
website: https://framedev.stream

commands:
  pay:
    description: Pay to another Player Money
  balance:
    aliases:
      - bal
    description: Show your Balance or from another Player
  economy:
    aliases:
      - eco
    description: Economy is the Upper Command for each Command
  balancetop:
    aliases:
      - baltop
  bank:
    description: Bank is the Command for al Sub Commands like bank create
  frameeconomy:
    aliases:
      - frameeco
permissions:
  frameeconomy.*:
    children:
      frameeconomy.balance: true
      frameeconomy.balance.others: true
      frameeconomy.balancetop: true
      frameeconomy.pay: true
      frameeconomy.eco.set: true
      frameeconomy.eco.set.others: true
      frameeconomy.bank.create: true
      frameeconomy.bank.balance: true
      frameeconomy.bank.deposit: true
      frameeconomy.bank.withdraw: true
      frameeconomy.eco.status: true
      frameeconomy.reload: true
  frameeconomy.balance:
    default: op
  frameeconomy.balance.others:
    default: op
    children:
      frameeconomy.balance: true
  frameeconomy.pay:
    default: op
  frameeconomy.eco.set:
    default: op
  frameeconomy.eco.set.others:
    default: op
    children:
      frameeconomy.eco.set: true
  frameeconomy.balancetop:
    default: op
  frameeconomy.bank.create:
    default: op
  frameeconomy.bank.balance:
    default: op
  frameeconomy.bank.deposit:
    default: op
  frameeconomy.bank.withdraw:
    default: op
  frameeconomy.set.status:
    default: op
  frameeconomy.reload:
    default: op