Prefix: '&6[&aFrame&bEconomy&6] &c>> &7'

#MySQL Connection!
MySQL:
  Host: 'localhost'
  User: 'root'
  Password: 'password'
  Database: 'database'
  Port: 3306
  Use: false
SQLite:
  Path: 'plugins/FrameEconomy/money'
  FileName: 'database'
  Use: false
MongoDB:
  Database: ' '
  User: ' '
  Password: ' '
  Host: ' '
  Port: 27017
  Localhost: false
  Normal: false
  Use: false
Currency:
  Plural: '$'
  Singular: '$'
Economy:
  MaxBalance: 1000000000
PayLoad:
  Use: false
  Time:
    Sec: 0
    Min: 30
    Hour: 0
    Day: 0
Interest:
  Use: false
  Time:
    Sec: 0
    Min: 0
    Hour: 1
    Day: 0