name: FrameEconomy
version: @version@
description: Money System works with Vault
main: de.framedev.frameeconomy.main.Main
api-version: 1.16
depend: [ Vault ]
authors: [ FrameDev ]
website: https://framedev.stream

commands:
  pay:
  balance:
    aliases:
      - bal
  economy:
    aliases:
      - eco
permissions:
  frameeconomy.*:
    children:
      frameeconomy.balance: true
      frameeconomy.balance.others: true
      frameeconomy.pay: true
      frameeconomy.eco.set: true
      frameeconomy.eco.set.others: true
  frameeconomy.balance:
    default: op
  frameeconomy.balance.others:
    default: op
    children:
      frameeconomy.balance: true
  frameeconomy.pay:
    default: op
  frameeconomy.eco.set:
    default: op
  frameeconomy.eco.set.others:
    default: op
    children:
      frameeconomy.eco.set: true